name: Deploy to cPanel via FTPS

on:
  push:
    branches:
      - master # Change to your branch name

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.gope.rw
          username: ${{ secrets.FTP_PASSWORD }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps # Use FTPS instead of FTP
          port: 21
          local-dir: ./ # Change if needed
          server-dir: /public_html/ # Adjust based on your hosting structure
